//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigalev_API_beautiful_places.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeautifulPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeautifulPlace()
        {
            this.Favorites = new HashSet<Favorites>();
            this.Grades = new HashSet<Grades>();
        }
    
        public int id_beautiful_place { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_user { get; set; }
        public int id_address { get; set; }
        public int id_type_locality { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string main_image { get; set; }
        public bool accepted { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual TypeLocalitys TypeLocalitys { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grades> Grades { get; set; }
    }
}
