//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pigalev_API_beautiful_places.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int id_image { get; set; }
        public string image { get; set; }
        public int id_beautiful_place { get; set; }
    
        public virtual BeautifulPlace BeautifulPlace { get; set; }
    }
}
